# Generated by Django 5.2.4 on 2025-07-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cablepackage_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
