# Generated by Django 5.2.4 on 2025-07-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_tx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
