# Generated by Django 5.2.4 on 2025-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='response_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
